---
title: The Effects of Distance, Number of Layovers, and Geography on Average Plane
  Ticket Price
author: "Kushin Mukherjee and Jordan Buhmann"
date: "10/22/2018"
output:
  word_document: default
  html_document: default
---
## Abstract

## Introduction

For many, finding an affordable plane ticket for their next trip can be difficult. Prices can widly vary between locations and at different times of the year, for seemingly unknown reasons. In this report, we attempt to find statistically significant variables that effect the price of a domestic plane ticket in the United States. We use data containing a sample of U.S. domestic itineraries from 2017, all of which involve a New York airport. This data set contains various information on these flights, including time of year the flight occured, airport of departure and arrival, number of layovers, and of course market price of the ticket, to name a few. We take these data and apply Multiple Linear Regression models on them to understand the effect they have on the price of the ticket. We find an interesting equation to predict the price of a plane ticket using a few statistically significant variables.

Given that for the data we have, each of our observations relate to the state of NY in some way, we thought it would be interesting to look at airfare trends as they relate to flights flying into and leaving the state, and check to see if there are any notable differences between these two groups of flights.

Some commonplace observations that frequent flyers make is that for flights across larger distances, breaking the journey into smaller legs helps reduce the overall cost of the journey. Thus, when flying across large distances on a budget, flyers sometimes look out for flights with one or more layovers. Perhaps the cost in time is sometimes worth the discount in ticket fare.
Another observation, which is almost patent, is that flights become much more expensive during certain times of year - notably during the holiday season. So we might expect journeys during a particular time of year to be more expensive than the same journey during other times.
With these motivating questions, we decided to conduct some statistical analyses to see how well these folk observations hold up to empirical data.

## Methods
In order to create a model on the average price of a plane ticket, the backward elimination method was used. We started with a Multiple Linear Regression model containing the variables "Quarter," which was a number 1-4 corresponding to which season the flight took place in, "Passengers," which was a number showing how many passangers paid the same fare for an itinerary, "Market Distance," which was the total distance in miles covered by the itinerary, "Geography Type," which was a number 1 or 2 for if the itineary was non-contiguous domestic or contiguous domestic, and "Number Layovers," which was a number 0 through 2 corresponding to the number of layovers in the itinerary. Creating this model, the p-values of each individual variable were examined. Then, the variable containing the highest p-value over 0.05 was eliminated, and another model was without that variable. This process was repeated until only variables with a p-value below 0.05 remain. The following equation shows the full model with all possible predictors:
$$\widehat{Fare} = \beta_0 +\beta_1MarketDistance +\beta_2NumberLayovers + \beta_3Geography + \beta_4Quarter + \beta_5Passengers$$
The following equation shows the resulting model after backward elimination:
$$\widehat{Fare} = \beta_0 +\beta_1 MarketDistance +\beta_2NumberLayovers + \beta_3Geography$$
Then, an f-test was performed between the model containing only the statistically significant variables and a model containing Market Price compared to no variables. This was done to see if the created model will actually show a siginficant effect on Market Price. 

Next, since we were also interested in looking at differences between journeys that were ending in NY versus those that were beginning at NY, we divided our dataset into itineraries of flights that departed from NY and flights that landed in NY.
There were 4 journeys in the dataset that both began and ended in NY, and we included them in both groups.
Henceforth, the group that included flights that landed in NY will be referred to as the incoming group and the group that included flights that departed from NY will be referred to as the outgoing group.

For each group we found the average flight fare and average number of layovers for flights between NY and all other states. For the incoming group there was data present for 40 states whereas for the outgoing group there was data for 37 states. Since there are multiple airports per state and we were looking at state-state itineraries, we also decided to find the average distance between the starting and ending points of the journey for a given pair of states.

Since flight fare was our dependent variable of interest, we began by fitting 2 multiple linear models, one for each group, where the predictors were mean distance of the journey and mean number of layovers.
Our model can be represented by the following equation - 
$$\widehat{Fare} = \beta_0 +\beta_1 Mean Distance +\beta_2MeanLayovers $$
We also fit a version of these models with an interaction term for mean distance and mean number of layovers. The rationale for this was that while we expect longer journeys to naturally be more expensive, having a journey with one or more layovers may mitigate some of those costs.
This model could be expressed as - 

$$\widehat{Fare} = \beta_0 +\beta_1 Mean Distance +\beta_2MeanLayovers + \beta_3MeanDistance\times MeanLayovers$$
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
# To see full results, uncomment code with two hashtags.
library(ggplot2)
library(dplyr)
raw_data<- read.csv('itineraries-2017.csv')

#Using all the numerical variables in the data to create a full model on MARKET_FARE
model1<- lm(MARKET_FARE~QUARTER + PASSENGERS + MARKET_DISTANCE + ITIN_GEO_TYPE + numLayovers, data=raw_data)
##summary(model1)

# QUARTER has the highest p-value in the previous model, so model2 contains every variable except for QUARTER.
model2<- lm(MARKET_FARE~PASSENGERS + MARKET_DISTANCE + ITIN_GEO_TYPE + numLayovers, data=raw_data)
##summary(model2)

# PASSENGERS has the highest p-value in the previous model, so model3 contains every variable except for PASSENGERS. The p-value of these predictors are all less than 0.05, so this is our final model.
model3<- lm(MARKET_FARE~MARKET_DISTANCE + ITIN_GEO_TYPE + numLayovers, data=raw_data)
##summary(model3)

# Creating a model with no predictors to use in the following f-test
model4<- lm(MARKET_FARE~1, data=raw_data)
##summary(model4)

# Perform an f-test between model3 and model4.
ft1 <- anova(model4, model3)
##ft1

# Creating a scatterplot between MARKET_DISTANCE and MARKET_FARE
ggplot()+geom_point(aes(x=MARKET_DISTANCE, y=MARKET_FARE), data=raw_data) + xlab("Distance (in Miles)") + ylab("Market Price (in Dollars)") + ylim(0,1500) + ggtitle("Figure 1. Scatterplot of Market Fare compared to Market Distance")

# Creating a boxplot between ITIN_GEO_TYPE and MARKET_FARE
ggplot()+geom_boxplot(aes(x=factor(ITIN_GEO_TYPE), y=MARKET_FARE), data=raw_data) + xlab("Geography Type") + ylab("Market Price (in Dollars)") + ggtitle("Figure 2. Boxplot of Market Fare compared to Geography Type") + ylim(0,1500)

# Creating a boxplot between numLayovers and MARKET_FARE
ggplot()+geom_boxplot(aes(x=factor(numLayovers), y=MARKET_FARE), data=raw_data) + xlab("Number of Layovers") + ylab("Market Price (in Dollars)") + ggtitle("Figure 3. Boxplot of Market Fare compared to the Number of Layovers") + ylim(0,1500)

# Calculating the confidence intervals of the slope estimates for each statistically significant variable.
##confint(model3, 'MARKET_DISTANCE' ,level=0.95)
##confint(model3, 'ITIN_GEO_TYPE' ,level=0.95)
##confint(model3, 'numLayovers' ,level=0.95)

#Subsetting for flights that leave from NY state
ny_data<- raw_data%>%filter(ORIGIN_STATE_ABR=='NY')
#Linear model where the predictor is a categorical variable for the the airport from which the plane departs
ny_model<- lm(MARKET_FARE~factor(ORIGIN), data= ny_data)
##summary(ny_model)

#creating a df which contains average fare and layovers for all flights leaving from NY, organized by state
mean_nyo_data<-raw_data%>%filter(ORIGIN_STATE_ABR=='NY')%>%group_by(DEST_STATE_ABR)%>%summarise(mean_fare= mean(MARKET_FARE), mean_dist = mean(MARKET_DISTANCE), num_lay= mean(numLayovers))

#creating a df which contains average fare and layovers for all flights arriving at NY, organized by state
mean_nyi_data<- raw_data%>%filter(DEST_STATE_ABR=='NY')%>%group_by(ORIGIN_STATE_ABR)%>%summarise(mean_fare= mean(MARKET_FARE), mean_dist = mean(MARKET_DISTANCE), num_lay= mean(numLayovers))


#Full and reduced models for obtaining expected mean fare from mean distance and mean layovers. Reduced model does not have the interaction term. This set of models is for outgoing flights data
model5<-lm(mean_fare~ mean_dist+num_lay+num_lay*mean_dist, data= mean_nyo_data)
model6<-lm(mean_fare~ mean_dist+num_lay, data= mean_nyo_data)
##summary(model5)
##summary(model6)

#F-test to compare full and reduced models
ft2<-anova(model5,model6)
##ft2


#Full and reduced models for obtaining expected mean fare from mean distance and mean layovers. Reduced model does not have the interaction term. This set of models is for incoming flights data
model7<-lm(mean_fare~ mean_dist+num_lay+num_lay*mean_dist, data= mean_nyi_data)
model8<-lm(mean_fare~ mean_dist+num_lay, data= mean_nyi_data)
##summary(model7)
##summary(model8)

#F-test to compare full and reduced models
ft3<-anova(model7,model8)
##ft3

#Exploratory plot to look at how distance and number of layovers relates to fares for outgoing flights

ggplot()+geom_point(aes(x=mean_dist, y=mean_fare, col=num_lay), data=mean_nyo_data) + ggtitle("Figure 4. Scatterplot of Mean Fare Compared to Mean Distance and Mean Layovers for Outgoing Flights")
ggplot()+geom_point(aes(x=mean_dist, y=mean_fare, col=num_lay), data=mean_nyi_data) ("Figure 5. Scatterplot of Mean Fare Compared to Mean Distance and Mean Layovers for Incoming Flights")

#Generic code for obtaining conf intervals for slope estimates
##confint(model7, 'mean_dist:num_lay' ,level=0.95)



```

## Results
When performing the backward elimation model, we first start with our full model containing the "Quarter", "Passengers", "Market Distance", "Geography Type", and "Number of layovers" varaibles. The p-value of the "Quarter" variable is the highest with 0.851. This is greater than 0.05, so this variable will be eliminated from our model. In our new reduced model, the p-value of "Passengers" is the highest with 0.100. This is also greater than 0.05, so this variable will be eliminated from our model as well. In the next reduced model, the p-value of "Geography Type" is the highest with 0.013. This is less than 0.05, meaning it should stay in our model 


Next, we will the examine the results of incoming and outgoing flights.
Incoming Group -  

For our 'reduced' model without the interaction term, we achieve statistical significance for the estimated slope coefficient for mean distance. The estimated slope coefficient for mean distance is 0.16776 (95 CI: 0.1043711 - 0.2311455). This model has a Multiple R-squared value of 0.5465.

For our 'full' model, which includes the interaction term, we achieve statistical significance for the slope coefficients for the main effect of average layovers and the interaction term as well. The estimated slope coefficient for average number of layovers is -238.57968 (95 CI: -448.8797 - -28.27968) and the estimated slope coefficient for the interaction term is 0.20031 (95 CI: 0.08791061 - 0.3127084 )

An F-test comparing the full and reduced models yielded an F value of 9.0017 (p = 0.005103)

Outgoing Group - 

For our 'reduced' model without the interaction term, we achieve statistical signficance for the slope coefficients for mean distance and mean number of layovers. The estimated slope coefficient for mean distance is 0.06566 (95 CI: 0.02868519 - 0.1026327) and for mean layovers is 139.15076 (95 CI: 56.69137 - 221.6102). The Multiple R-squared value for this model is 0.5916.

For our 'full' model, which includes the interation term, we fail to achieve statistical significance for the estimated slope coefficients for any of the main terms, but we do achieve statistical significance for the estimate slope coefficient for the interaction term. The estimated slope coefficient for the interaction term is 7.076e-02 (95 CI: 0.02277662 - 0.11874). The Multiple R-squared value for this model is 0.6791.

An F-test comparing the full and reduced models yielded an F value of 13.063 (p = 0.0009133)



## Discussion

## Conclusion